#!/bin/bash
# testing the else section
testuser=badtest
if grep $testuser /etc/passwd
then
    echo The files for tuser $testuser are:
    ls -a /home/$testuser/*.b*
else
    echo "The user name $testuser does not exist on the system"
fi
