#!/bin/bash
# iterate through multiple directories

for file in /home/wilson/.b* /home/wilson/badtest
do
    if [ -d "$file" ]
    then
        echo "$file is a directory"
    elif [ -f "$file" ]
    then
        echo "$file is a file"
    else
        echo "$file does't exist"
    fi
done
